# infra/hosts.yaml
kubernetes_controller:
  - name: rke2-controller
    ip: 192.168.10.40
    username: Admin
    ssh_key_path: /Users/alexelwell/Documents/SSH/zeus_template_ssh
    gateway: 192.168.10.1
    tags: ["rancher", "controller"]
    vcpu: 4
    memory: 8192
    disk_size: 64
    disk_device: "scsi0"
    dns: 192.168.10.1
kubernetes_workers:
  - name: rke2-worker-1
    ip: 192.168.10.41
    username: Admin
    ssh_key_path: /Users/alexelwell/Documents/SSH/zeus_template_ssh
    gateway: 192.168.10.1
    tags: ["rancher", "docker"]
    vcpu: 5
    memory: 4096
    disk_size: 32
    disk_device: "scsi0"
    dns: 192.168.10.1
  - name: rke2-worker-2
    ip: 192.168.10.42
    username: Admin
    ssh_key_path: /Users/alexelwell/Documents/SSH/zeus_template_ssh
    gateway: 192.168.10.1
    tags: ["rancher", "docker"]
    vcpu: 5
    memory: 4096
    disk_size: 32
    disk_device: "scsi0"
    dns: 192.168.10.1
  - name: rke2-worker-3
    ip: 192.168.10.43
    username: Admin
    ssh_key_path: /Users/alexelwell/Documents/SSH/zeus_template_ssh
    gateway: 192.168.10.1
    tags: ["rancher", "docker"]
    vcpu: 5
    memory: 4096
    disk_size: 32
    disk_device: "scsi0"
    dns: 192.168.10.1
portainer:
  - name: portainer
    ip: 192.168.10.60
    username: Admin
    ssh_key_path: /Users/alexelwell/Documents/SSH/zeus_template_ssh
    gateway: 192.168.10.1
    tags: ["rancher", "docker"]
    vcpu: 4
    memory: 6144
    disk_size: 32
    disk_device: "scsi0"
    dns: 192.168.10.1
