# /opt/sonarqube/docker-compose.yml
version: "3"
services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on: [db]
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://192.168.10.50:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonardata:/opt/sonarqube/data
volumes:
  dbdata:
  sonardata:
