version: "3"
services:
  sonarqube:
    image: sonarqube:community
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://192.168.10.50:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: ${psqlPassword}
    ports:
      - "9100:9000"
    volumes:
      - sonardata:/opt/sonarqube/data
volumes:
  dbdata:
  sonardata:
