image:
  repository: ghcr.io/ae-enterprise/grow_project/plants
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret

env:
  DATABASE_URL: "postgres://user:password@plants-db:5432/plants"
