image:
  repository: ghcr.io/ae-enterprise/grow_project/plants
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret

env:
  DB_NAME: grow_project
  DB_USER: postgres
  DB_PASSWORD: postgres #TODO - make this a secret!
  DB_HOST: localhost
  DB_PORT: 5432
