FROM python:3.11-slim

WORKDIR /app
# Copy only required files
COPY packages.txt /app/
COPY manage.py /app/
COPY inventory/*.py /app/inventory/
COPY plants_service/*.py /app/plants_service/
# Do not copy .env

RUN pip install --upgrade pip && \
    pip install -r packages.txt

EXPOSE 8001
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
