name: Build Docker
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-all-dockerfiles:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign (not on PRs)
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: "v2.2.4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to GHCR (not on PRs)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find all Dockerfiles
        id: find_dockerfiles
        run: |
          find . -name 'Dockerfile.prod' > dockerfiles.txt
          echo "Found Dockerfiles:"
          cat dockerfiles.txt

      - name: Build and push all Docker images
        run: |
          while read dockerfile; do
            dir=$(dirname "$dockerfile")
            name=$(echo "$dir" | sed 's|^\./||; s|/|-|g')  # Convert path to valid image suffix
            full_image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${name:-root}"

            echo "Building and pushing $full_image from $dir"

            docker buildx build \
              --push=${{ github.event_name != 'pull_request' }} \
              --tag "$full_image" \
              --file "$dockerfile" \
              "$dir"

            echo "$full_image" >> images.txt
          done < dockerfiles.txt

      - name: Sign images (not on PRs)
        if: github.event_name != 'pull_request'
        run: |
          while read image; do
            digest=$(crane digest "$image")
            echo "Signing $image@$digest"
            cosign sign --yes "$image@$digest"
          done < images.txt
